#server:
#  port: 8081
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pairing?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    username: root
#    password: 68082775
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#
#jwt:
#  expiration: 25200
#  secret: gkfrjsjanaksgdktjdhkswjsfjrzlqlzlwksgdkdmddo
#
#security:
#  oauth2:
#    client:
#      registration:
#        kakao:
#          client-id: e2d9ca4cc88e3d05c49ea1e87eb1d2af
#          client-secret: 9Sd2QtJ6YXpJzk0pLeitKYHEtZ7iHEfZ
#          redirect-uri: http://223.130.150.111:8081/member/naver/callback
#          grant-type: authorization_code
#          authorize-uri: https://kauth.kakao.com/oauth/authorize # 테스트 단계
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#        naver:
#          client-id: aNBRwn5SHZAN0P1ILTeR
#          client-secret: dRc8LwuFv5
#          redirect-uri: http://223.130.150.111:8081/member/naver/callback
#          authorize-uri: https://nid.naver.com/oauth2.0/authorize # 테스트 단계
#          grant-type: authorization_code
#          token-uri: https://nid.naver.com/oauth2.0/token
#          user-info-uri: https://openapi.naver.com/v1/nid/me
#cloud:
#  ncp:
#    storage:
#      end-point: https://kr.object.ncloudstorage.com
#      region-name: kr-standard
#      bucket-name-member: pairing-member
#      access-key: ncp_iam_BPAMKR1mHeuc9rnvTiRt
#      secret-key: ncp_iam_BPKMKR3rUgjamkRkqg5DXPHXLVY2siewl0

server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pairing?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 68082775
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

jwt:
  expiration: 2520000
  secret: gkfrjsjanaksgdktjdhkswjsfjrzlqlzlwksgdkdmddo

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: e2d9ca4cc88e3d05c49ea1e87eb1d2af
          client-secret: 9Sd2QtJ6YXpJzk0pLeitKYHEtZ7iHEfZ
          redirect-uri: http://localhost:8081/member/naver/callback
          grant-type: authorization_code
          authorize-uri: https://kauth.kakao.com/oauth/authorize # 테스트 단계
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
        naver:
          client-id: aNBRwn5SHZAN0P1ILTeR
          client-secret: dRc8LwuFv5
          redirect-uri: http://localhost:8081/member/naver/callback
          authorize-uri: https://nid.naver.com/oauth2.0/authorize # 테스트 단계
          grant-type: authorization_code
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
cloud:
  ncp:
    storage:
      end-point: https://kr.object.ncloudstorage.com
      region-name: kr-standard
      bucket-name-member: pairing-member
      bucket-name-community: pairing-board
      access-key: ncp_iam_BPAMKR1mHeuc9rnvTiRt
      secret-key: ncp_iam_BPKMKR3rUgjamkRkqg5DXPHXLVY2siewl0


